services:
  - type: web
    name: built-theory-app
    env: python
    # We use buildCommand to update the Linux system and install LibreOffice
    # then install your Python requirements.
    buildCommand: |
      apt-get update && apt-get install -y libreoffice
      pip install -r requirements.txt
    # This points to your 'app.py' file. Gunicorn is better for production.
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: TEMP_DIR
        value: /tmp/built-theory-temp